=== VitaminCtea/JavaPractice/readXML/testDTD.dtd
<!--
    文档类型规则，相当于在XML文件中书写<!DOCTYPE rootElement [ 每个元素的规则... ]>
    元素属性规则：<!ATTLIST element attribute type default>
    元素规则：<!ELEMENT element (child..., (child...))>
    #PCDATA表示文本
-->

<!ELEMENT config (entry)+>
<!ELEMENT entry (font|color)>

<!ATTLIST entry id ID #REQUIRED>
<!ATTLIST font id ID #IMPLIED>
<!ATTLIST name id ID #IMPLIED>
<!ATTLIST size id ID #IMPLIED>

<!ELEMENT font (name, size)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT size (#PCDATA)>

<!ELEMENT color (red, green, blue)>
<!ELEMENT red (#PCDATA)>
<!ELEMENT green (#PCDATA)>
<!ELEMENT blue (#PCDATA)>

=== VitaminCtea/JavaPractice/readXML/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 指定文档类型规则 -->
<!DOCTYPE config SYSTEM "readXML/testDTD.dtd">
<config>
    <entry id="test">
        <font id="font">
            <name id="person">Tom</name>
            <size id="age">31</size>
        </font>
    </entry>
    <entry id="title">
        <font>
            <name>Helvetica</name>
            <size>36</size>
        </font>
    </entry>
    <entry id="body">
        <font>
            <name>Times Roman</name>
            <size>12</size>
        </font>
    </entry>
    <entry id="background">
        <color>
            <red>0</red>
            <green>50</green>
            <blue>100</blue>
        </color>
    </entry>
</config>
