=== VitaminCtea/JavaPractice/readXML/writeDTD.dtd
<!ELEMENT config (entry+,note)>
<!ELEMENT entry (font+)>
<!ATTLIST entry id CDATA #IMPLIED>
<!ATTLIST entry value CDATA #IMPLIED>
<!ELEMENT note (to,from,heading,body,koko)>
<!ELEMENT font (name,size)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT body (#PCDATA)>
<!ELEMENT koko EMPTY>
<!ELEMENT name (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ATTLIST size id CDATA #IMPLIED>

=== VitaminCtea/JavaPractice/readXML/write.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config SYSTEM "writeDTD.dtd">
<config>
    <entry id="test" value="entry">
        <font>
            <name>lala</name>
            <size>90</size>
        </font>
        <font>
            <name>Tom</name>
            <size id="999">31</size>
        </font>
    </entry>
    <entry id="title" value="entry">
        <font>
            <name>lala</name>
            <size>90</size>
        </font>
        <font>
            <name>Helvetica</name>
            <size id="999">36</size>
        </font>
    </entry>
    <entry>
        <font>
            <name>lala</name>
            <size>90</size>
        </font>
    </entry>
    <note>
        <to>George</to>
        <from>John</from>
        <heading>Reminder</heading>
        <body>Don't forget the meeting!</body>
        <koko/>
    </note>
</config>
